### ISSUE TITLE
Applying additional modifications: error cannot find symbol for Custom app React Element panic: runtime error: index out of range [0] with length 0

### ISSUE THREAD

**Issue by Levkia14** [spicetify/spicetify-marketplace#187]
### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: Spotify  pour Windows
1.1.85.895.g2a71e1b8
- Spicetify version: Lastest
```

### 📝 Description

Hello i have this error:
spicetify v2.9.8
Copying raw assets:
OK
Overwriting themed assets:
OK
Transferring user.css:
OK
Applying additional modifications:
error cannot find symbol for Custom app React Element
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
github.com/spicetify/spicetify-cli/src/apply.insertCustomApp.func1({0xc000ab8000, 0x18aa98})
        /home/runner/work/spicetify-cli/spicetify-cli/src/apply/apply.go:220 +0x987
github.com/spicetify/spicetify-cli/src/utils.ModifyFile({0xc000389b00, 0x38}, 0xc0001058d8)
        /home/runner/work/spicetify-cli/spicetify-cli/src/utils/utils.go:191 +0x7b
github.com/spicetify/spicetify-cli/src/apply.insertCustomApp({0xc000389b00, 0x3b}, {{0xc0000447e0, 0x2, 0x2}, {0xc000044820, 0x1, 0x2}, 0x1, 0x1, ...})
        /home/runner/work/spicetify-cli/spicetify-cli/src/apply/apply.go:188 +0x90
github.com/spicetify/spicetify-cli/src/apply.AdditionalOptions({0xc00000ab40, 0x2b}, {{0xc0000447e0, 0x2, 0x2}, {0xc000044820, 0x1, 0x2}, 0x1, 0x1, ...})
        /home/runner/work/spicetify-cli/spicetify-cli/src/apply/apply.go:37 +0x4c3
github.com/spicetify/spicetify-cli/src/cmd.Apply({0xfcb7f8, 0x5})
        /home/runner/work/spicetify-cli/spicetify-cli/src/cmd/apply.go:72 +0x9ae
main.main()
        /home/runner/work/spicetify-cli/spicetify-cli/spicetify.go:225 +0x77b

### 📸 Screenshots

https://prnt.sc/XVvwXpBVfmkg

**Comment by jix1351** [comment]
same

**Comment by theRealPadster** [comment]
Not related to Marketplace at all. Transferring to spicetify-cli.
