### ISSUE TITLE
Runtime Error when running Spicetify Apply

### ISSUE THREAD

**Issue by WooxHimself** [spicetify/spicetify-marketplace#191]
### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.1.85
- Spicetify version: 2.9.8
- Windows 11
```

### 📝 Description

Installation went fine, but when I ran `spicetify apply` I get this error:

```
PS C:\Users\*****> spicetify apply
spicetify v2.9.8
Overwriting raw assets:
OK
Transferring user.css:
OK
Applying additional modifications:
error cannot find symbol for Custom app React Element
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
github.com/spicetify/spicetify-cli/src/apply.insertCustomApp.func1({0xc000ab8000, 0x18aa98})
        /home/runner/work/spicetify-cli/spicetify-cli/src/apply/apply.go:220 +0x987
github.com/spicetify/spicetify-cli/src/utils.ModifyFile({0xc00000f040, 0x38}, 0xc0000cb8d8)
        /home/runner/work/spicetify-cli/spicetify-cli/src/utils/utils.go:191 +0x7b
github.com/spicetify/spicetify-cli/src/apply.insertCustomApp({0xc00000f040, 0x3b}, {{0xc00016a060, 0x1, 0x2}, {0xc00016a080, 0x1, 0x2}, 0x1, 0x1, ...})
        /home/runner/work/spicetify-cli/spicetify-cli/src/apply/apply.go:188 +0x90
github.com/spicetify/spicetify-cli/src/apply.AdditionalOptions({0xc00000cae0, 0x2b}, {{0xc00016a060, 0x1, 0x2}, {0xc00016a080, 0x1, 0x2}, 0x1, 0x1, ...})
        /home/runner/work/spicetify-cli/spicetify-cli/src/apply/apply.go:37 +0x4c3
github.com/spicetify/spicetify-cli/src/cmd.Apply({0x65b7f8, 0x5})
        /home/runner/work/spicetify-cli/spicetify-cli/src/cmd/apply.go:72 +0x9ae
main.main()
        /home/runner/work/spicetify-cli/spicetify-cli/spicetify.go:225 +0x77b
```

### 📸 Screenshots

![image](https://user-images.githubusercontent.com/76164598/169139463-e1aa30a0-e8fd-47df-80cf-4d3a7d6eaf86.png)

**Comment by theRealPadster** [comment]
Unrelated to marketplace.
